name: Java Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set up java
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Compile java code
      run: javac Main.java
      working-directory: ./src/main/java/org/example

    - name: Compile java code
      run: ls
      working-directory: ./src/main/java/org/example


    - name: run java code
      run: java Main.class
      working-directory: ./src/main/java/org/example
